### ISSUE TITLE
New Version?

### ISSUE THREAD

**Issue by badger0** [Arengorn/AutoReply#1]
This doesn't seem to work - it's fairly straight forward to install, but testing seems to show it does not function as intended.
Installation was done according to instructions, I have other Lua plugins that function, and talking to a friend seemed to indicate the problem may be it's not version compatible with latest TS3 version. Any chance for an update?

**Comment by lovesegfault** [comment]
Heya, I'll do some testing later today to check if I can get this working again, thanks for the report!

**Comment by badger0** [comment]
After the latest update to TS it's suddenly working again. No need! :)

**Comment by lovesegfault** [comment]
Great!
